### ISSUE TITLE
pull access denied for registry.baidubce.com/easyfaas-public/runner-runtime

### ISSUE THREAD

**Issue by huailide** [baidu/EasyFaaS#4]
According to "getting-started-docker-compose.md",
When I use the command "sh app_control.sh start"
I get the information as:
Pulling runtime (registry.baidubce.com/easyfaas-public/runner-runtime:demo1.0)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling runtime (registry.baidubce.com/easyfaas-public/runner-runtime:demo1.0)...
ERROR: pull access denied for registry.baidubce.com/easyfaas-public/runner-runtime, repository does not exist or may require 'docker login': denied: requested accessto the resource is denied

**Comment by flyingfang** [comment]
Thank you for your feedback. I have resolved the problem. Please try it again.

**Comment by huailide** [comment]
still not work
[root@KSSHUAT00850 /opt/EasyFaaS/scripts/docker-compose/compose-local]# sh app_control.sh start
Pulling funclet (registry.baidubce.com/easyfaas-public/mini-funclet:demo1.0)...
ERROR: manifest for registry.baidubce.com/easyfaas-public/mini-funclet:demo1.0 not found: manifest unknown: manifest unknown

**Comment by huailide** [comment]
> Thank you for your feedback. I have resolved the problem. Please try it again.

still not work,what is the correct image tag?
demo1.0 is not correct
[root@KSSHUAT00850 /opt/EasyFaaS/scripts/docker-compose/compose-local]# sh app_control.sh start
Pulling funclet (registry.baidubce.com/easyfaas-public/mini-funclet:demo1.0)...
ERROR: manifest for registry.baidubce.com/easyfaas-public/mini-funclet:demo1.0 not found: manifest unknown: manifest unknown

**Comment by flyingfang** [comment]
> > Thank you for your feedback. I have resolved the problem. Please try it again.
> 
> still not work,what is the correct image tag?
> demo1.0 is not correct
> [root@KSSHUAT00850 /opt/EasyFaaS/scripts/docker-compose/compose-local]# sh app_control.sh start
> Pulling funclet (registry.baidubce.com/easyfaas-public/mini-funclet:demo1.0)...
> ERROR: manifest for registry.baidubce.com/easyfaas-public/mini-funclet:demo1.0 not found: manifest unknown: manifest unknown

Sorry for trouble you. I have verified the tag. Give it a try later.
